### ISSUE TITLE
Add instructions for compiling without XCode?

### ISSUE THREAD

**Issue by karlhorky** [patrickjane/fixmouse#1]
Hi, first of all, thanks for this! Really appreciate projects like these, improving the weird UX decisions made by Apple.

I was trying to build from source, so that I could contribute instructions to the readme, but I was unable to make it work.

Maybe it's not possible without XCode?

```bash
gcc main.m -framework Foundation -framework IOKit -o fixmouse
main.m:7:4: error: use of undeclared identifier 'NXEventHandle'
   NXEventHandle handle = MACH_PORT_NULL;
   ^
main.m:20:79: error: use of undeclared identifier 'handle'
      res = IOServiceOpen(service, mach_task_self(), kIOHIDParamConnectType, &handle);
                                                                              ^
main.m:23:52: error: expected ')'
      res = IOHIDCopyCFTypeParameter(handle, CFSTR(kIOHIDMouseAccelerationType), &typeRef);
                                                   ^
main.m:23:46: note: to match this '('
      res = IOHIDCopyCFTypeParameter(handle, CFSTR(kIOHIDMouseAccelerationType), &typeRef);
                                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h:195:76: note: expanded from macro 'CFSTR'
#define CFSTR(cStr)  ((CFStringRef) __builtin___CFStringMakeConstantString ("" cStr ""))
                                                                           ^
main.m:23:38: error: use of undeclared identifier 'handle'
      res = IOHIDCopyCFTypeParameter(handle, CFSTR(kIOHIDMouseAccelerationType), &typeRef);
                                     ^
4 errors generated.
```

**Comment by patrickjane** [comment]
Actually, I thought I had made this repo private, as I found that its not working as great as expected 🤔

Anyway, I think it will be hardly possible to just compile the source file, you would need the full XCode project, which is not part of the repository.

**Comment by karlhorky** [comment]
> I found that its not working as great as expected 🤔

Oh, too bad :( What are the issues you're experiencing?

I suppose I'll close this issue for now.

**Comment by patrickjane** [comment]
Well, it did not remove mouse acceleration as expected. There was a tool I had been using for years which did a great job, and it used older macOS APIs. This API had been removed at some point however, so the tool no longer worked.

I attempted to reimplement it using the same code but up to date macOS APIs, but it didnt work out well it seems. By the way, it should not be necessary to compile this tool, there is precompiled releases available here https://github.com/patrickjane/fixmouse/releases/tag/1.0.0

**Comment by karlhorky** [comment]
> Well, it did not remove mouse acceleration as expected. There was a tool I had been using for years which did a great job, and it used older macOS APIs

Ah, ok, understood. I am just setting up a new Mac and I needed to install [SteelSeries ExactMouse](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/steelseries-exactmouse-tool.rb) again:

```bash
brew tap homebrew/cask-drivers
brew install --cask steelseries-exactmouse-tool
```

This works well, but I want to find an open source project.

> By the way, it should not be necessary to compile this tool, there is precompiled releases available here

Right yeah, I noticed those. I have been trying to dabble more with compiling Objective-C, Rust and Swift programs though, with the eventual goal of being able to write my own. I guess it is probably going to require a full XCode install...

**Comment by patrickjane** [comment]
I can just send you the full project, if you want, however it would need XCode to compile, yeah.

**Comment by karlhorky** [comment]
If there isn't any sensitive information in it, I suppose it could it just be added to this GitHub repo? Then others may also benefit from it somehow.

Maybe the problems could also be fixed, potentially with some hints like this repo: https://github.com/apsun/NoMouseAccel

**Comment by patrickjane** [comment]
https://github.com/patrickjane/fixmouse/releases/tag/1.0.1

Here you go. Making it part of the repo would require changing the folder structure, which I don't wanna do right now.

**Comment by karlhorky** [comment]
Cool, thanks!
